head:
  enableInTreeAutoscaling: true

  extraEnv:
    - name: RAY_memory_usage_threshold
      value: "0.99"

  resources:
    requests:
      cpu: "5"
      memory: "6Gi"
    limits:
      cpu: "5"
      memory: "6Gi"

worker:
  replicas: 1

  resources:
    requests:
      cpu: "1"
      memory: "3Gi"
    limits:
      cpu: "1"
      memory: "3Gi"
